openapi: 3.0.0
info:
  title: METAR, TAF & SIGMET Data API
  description: Provides real-time METARs, TAFs, and SIGMETs for airports and regions globally. Supports queries by ICAO airport ID, specific coordinates, or bounding box.
  version: 1.0.0
servers:
  - url: https://weather-data-eu.atmosoar.io/api
    description: Production Server
  - url: https://weather-data-test.atmosoar.io/api
    description: Test Server
paths:
  /metar/station/{icao}:
    get:
      summary: Get METAR data for the specified airport
      parameters:
        - name: icao
          in: path
          required: true
          schema:
            type: string
          description: ICAO code of the airport
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Data Not Available

  /metar/area:
    get:
      summary: Get METAR data for the specified area
      parameters:
        - name: north
          in: query
          required: true
          schema:
            type: number
            format: float
          description: North latitude of the area
        - name: south
          in: query
          required: true
          schema:
            type: number
            format: float
          description: South latitude of the area
        - name: east
          in: query
          required: true
          schema:
            type: number
            format: float
          description: East longitude of the area
        - name: west
          in: query
          required: true
          schema:
            type: number
            format: float
          description: West longitude of the area
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Data Not Available

  /taf/station/{icao}:
    get:
      summary: Get TAF data for the specified airport
      parameters:
        - name: icao
          in: path
          required: true
          schema:
            type: string
          description: ICAO code of the airport
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Data Not Available

  /sigmet/point:
    get:
      summary: Get SIGMET data for the specified point
      parameters:
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Latitude of the point
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Longitude of the point
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Data Not Available

  /sigmet/area:
    get:
      summary: Get SIGMET data for the specified area
      parameters:
        - name: lat1
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Latitude of the top-left corner
        - name: lon1
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Longitude of the top-left corner
        - name: lat2
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Latitude of the bottom-right corner
        - name: lon2
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Longitude of the bottom-right corner
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Data Not Available
