openapi: 3.0.0
info:
  title: Quick Token API (Weather Data)
  version: 1.0.0
servers:
  - url: https://weather-data-eu.atmosoar.io/api/auth
    description: Production server
  - url: https://weather-data-test.atmosoar.io/api/auth/
    description: Test server
paths:
  /get-quick-token:
    get:
      summary: Get quick token
      description: Generates a quick token (JWT) using your API Key.
      parameters:
        - name: key
          in: query
          required: true
          description: Your API Key
          schema:
            type: string
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuickTokenResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    QuickTokenResponse:
      type: object
      properties:
        token:
          type: string
        tokenExpiration:
          type: string
          format: date-time
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
        traceId:
          type: string
